In [3]:
# ---- SETUP ----

import pandas as pd
import numpy as np

In [5]:
# ---- CARREGAR O DATASET ----

df = pd.read_csv("livros.csv", sep=";")
print(f"Shape: {df.shape}")

Shape: (11967, 5)

In [ ]:
# ---- Nivel 1. EXPLORAÇÃO INICIAL ----

# 1 - Exibindo as 5 primeiras linhas
print(df.head())

In [8]:
# 2 - Use info() e describe() para entender a estrutura. Anote: quais colunas têm tipo incorreto?

print(df.info())
print(df.describe)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11967 entries, 0 to 11966
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   titulo   11967 non-null  object
 1   autor    11955 non-null  object
 2   isbn     11209 non-null  float64
 3   paginas  11967 non-null  int64
 4   ano      11966 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 467.6+ KB
None
<bound method NDFrame.describe of                                    titulo                   autor  \
0                    Orçamento sem falhas           Nath Finanças
1                   Minha Sombria Vanessa  Kate Elizabeth Russell
2                                Recursão            Blake Crouch
3                    M, o Filho do Século         Antonio Scurati
4        Oblivion Song: Entre Dois Mundos          Robert Kirkman
...                                   ...                     ...
11962  Poemas completos de Alberto Caeiro         Fernando Pessoa
11963          Poesia de Álvaro de Campos         Fernando Pessoa
11964                             Ben-Hur           Lewis Wallace
11965                     Folhas de Relva            Walt Whitman
11966                O sermão da montanha          Huberto Rohden

               isbn  paginas     ano
0      9.786556e+12      128  2021.0
1      9.788551e+12      432  2020.0
2      9.788551e+12      320  2020.0
3      9.788551e+12      816  2020.0
4      9.788551e+12      136  2020.0
...             ...      ...     ...
11962  9.788572e+12      208  2007.0
11963  9.798572e+12      600  2007.0
11964  9.788572e+12      528  2006.0
11965  9.788572e+12      575  2005.0
11966  9.788572e+12      158  2003.0

[11967 rows x 5 columns]>

In [9]:
# 3 - Quantos valores nulos existem em cada coluna? Crie uma tabela resumo.

df.isnull().sum()

titulo       0
autor       12
isbn       758
paginas      0
ano          1
dtype: int64

In [10]:
# 4 - Existem livros com 0 páginas no dataset? Se sim, quantos? Filtre e exiba esses registros.

livros_zero_paginas = df[df["paginas"] == 0]

print("A quantidade de livros com 0 páginas é:", livros_zero_paginas.shape[0])

livros_zero_paginas

A quantidade de livros com 0 páginas é: 42

,titulo,autor,isbn,paginas,ano
15,DUPLICADO Este é o Mar,Mariana Enriquez,9.788551e+12,0,2020.0
142,O Caso Da Mansão Deboën,Edgar Cantero,9.788551e+12,0,2019.0
155,Mundo Em Caos (Vol. 1),Patrick Ness,9.788551e+12,0,2019.0
179,Matadouro-Cinco,Kurt Vonnegut,9.788551e+12,0,2019.0
204,Coleção Josh Malerman,NaN,9.788551e+12,0,2019.0
207,Coleção R.J. Palácio,R.J. Palacio,9.788551e+12,0,2019.0
248,Uma Vida No Escuro,NaN,9.788581e+12,0,2018.0
303,Kit Livros Isabela Fretas - Não Se Apega não/N...,Isabela Freitas,9.788551e+12,0,2018.0
591,O regresso,Michael Punke,9.788581e+12,0,2016.0
592,O regresso,Michael Punke,9.788581e+12,0,2016.0
598,Box Coleção Ditadura,Elio Gaspari,9.788581e+12,0,2016.0
755,Elon Musk,Ashlee Vance,9.788581e+12,0,2015.0
761,Os Arquivos Perdidos: Box digital com 15 e-books,Pittacus Lore,9.788581e+12,0,2015.0
881,DE VOLTA A PARADISE,Pittacus Lore,9.788581e+12,0,2014.0
1110,"Bilionários por acaso: A criação do facebook, ...",Bem Mezrich,9.788581e+12,0,2012.0
1194,Reflexos,Intrínseca,NaN,0,2010.0
1321,As doze tribos de Hattie,Ayana Mathis,9.788581e+12,0,1969.0
1325,Claros sinais de loucura,Karen Harrington,9.788581e+12,0,1969.0
1326,Coleção Eu Me Chamo Antonio,Pedro Gabriel,9.788551e+12,0,1969.0
1327,Os diários do semideus,Rick Riordan,9.788581e+12,0,1969.0
2542,Amigos do peito,Vicky Ceelen,9.788575e+12,0,2003.0
2589,A Visualização Criativa Pode Mudar Sua Vida,Shakti Gawain,9.788587e+12,0,2002.0
4111,Classic,Galera Record,NaN,0,0.0
7576,O Espartilho,Lygia Fagundes Telles,NaN,0,1978.0
7711,As Regras de Ouro dos Casais Saudáveis,Augusto Cury,9.788542e+12,0,2020.0
7808,Ave Maria - O Santo Padre comenta o mistério d...,Papa Francisco,9.788542e+12,0,2019.0
7837,Box Monja Coen - Vol. 3,Monja Coen,9.788542e+12,0,2019.0
7898,1808 - Caixa,Laurentino Gomes,9.788577e+12,0,2018.0
8067,O Escravo - da África para a senzala. Ed. Econ...,NaN,9.788542e+12,0,2017.0
8521,"1808 : Como Uma Rainha Louca , Um Príncipe Med...",Laurentino Gomes,9.788577e+12,0,2012.0
8607,Evernight - Série Noite Eterna,Planeta do Brasil,NaN,0,2011.0
8621,DIARIO DA CAROL - 1,STANISIERE,9.788577e+12,0,2011.0
8811,O Escolhido,Planeta do Brasil,NaN,0,2009.0
9027,Jardim de menino poeta,Maria Valéria Rezende,9.788577e+12,0,2007.0
9563,Coletânea - Memórias De Carlota Joaquina E A B...,Marsilio Cassotti,9.788542e+12,0,1969.0
10264,A sabedoria do salgueiro,Verus,NaN,0,2003.0
10931,Paixao Irresistivel,Christina Lauren,9.788579e+12,0,2017.0
10942,Um Amor para Lady Johanna,Julie Garwood- Cely Couto,9.788550e+12,0,2017.0
11061,Audiobook O que é o Espiritismo,Allan Kardec,9.788579e+12,0,2015.0
11203,Tributo a Madonna,Universo dos Livros,NaN,0,2012.0
11245,Desejo,J. R. Ward,9.788579e+12,0,2011.0
11623,Por Trás Da Fama,M. S. Fayes,NaN,0,2019.0

In [11]:
# 5 - Quantos livros distintos foram publicados em cada ano? Use value_counts() e ordene cronologicamente.

df["ano"].value_counts().sort_index()

ano
0.0        12
1193.0      1
1862.0      1
1884.0      1
1931.0      1
         ...
2017.0    860
2018.0    655
2019.0    737
2020.0    591
2021.0      5
Name: count, Length: 66, dtype: int64

In [12]:
# ---- Nivel 2. TRANSFORMAÇÃO E LIMPEZA ----

# 1 - Crie uma coluna faixa_paginas com as categorias: "Curto" (<150), "Médio" (150–350) e "Longo" (>350). Use apply() com lambda.

df["faixa_paginas"] = df["paginas"].apply(
    lambda x: "Curto" if x < 150 else ("Médio" if x <= 350 else "Longo")
)

In [20]:
# 2 - Remova todos os registros onde paginas == 0 e salve em df_limpo. Quantos registros foram removidos?

df_limpo = df[df["paginas"] > 0].copy()

removidos = df.shape[0] - df_limpo.shape[0]
print("Foram removidos:", removidos, "registros")

Foram removidos: 42 registros

In [14]:
# 3 - Preencha os nulos da coluna ano com a mediana e converta para inteiro.

df_limpo["ano"] = df_limpo["ano"].fillna(df_limpo["ano"].median()).astype(int)

df_limpo["ano"].info()

<class 'pandas.core.series.Series'>
Index: 11925 entries, 0 to 11966
Series name: ano
Non-Null Count  Dtype
--------------  -----
11925 non-null  int64
dtypes: int64(1)
memory usage: 186.3 KB

In [15]:
# 4 - Crie uma coluna decada representando a década de publicação (ex: 2019 → 2010, 1987 → 1980).

df_limpo["decada"] = (df_limpo["ano"] // 10) * 10

print(df_limpo)

                                   titulo                   autor  \
0                    Orçamento sem falhas           Nath Finanças
1                   Minha Sombria Vanessa  Kate Elizabeth Russell
2                                Recursão            Blake Crouch
3                    M, o Filho do Século         Antonio Scurati
4        Oblivion Song: Entre Dois Mundos          Robert Kirkman
...                                   ...                     ...
11962  Poemas completos de Alberto Caeiro         Fernando Pessoa
11963          Poesia de Álvaro de Campos         Fernando Pessoa
11964                             Ben-Hur           Lewis Wallace
11965                     Folhas de Relva            Walt Whitman
11966                O sermão da montanha          Huberto Rohden

               isbn  paginas   ano faixa_paginas  decada
0      9.786556e+12      128  2021         Curto    2020
1      9.788551e+12      432  2020         Longo    2020
2      9.788551e+12      320  2020         Médio    2020
3      9.788551e+12      816  2020         Longo    2020
4      9.788551e+12      136  2020         Curto    2020
...             ...      ...   ...           ...     ...
11962  9.788572e+12      208  2007         Médio    2000
11963  9.798572e+12      600  2007         Longo    2000
11964  9.788572e+12      528  2006         Longo    2000
11965  9.788572e+12      575  2005         Longo    2000
11966  9.788572e+12      158  2003         Médio    2000

[11925 rows x 7 columns]

In [16]:
# ---- Nivel 3. ANÁLISE AVANÇADA (BONUS) ----

# 1 - Qual a média de páginas por década? Use groupby() e ordene da mais antiga para a mais recente.

media_paginas_por_decada = df_limpo.groupby("decada")["paginas"].mean().sort_index()

media_paginas_por_decada

decada
0       168.000000
1190    278.000000
1860    160.000000
1880    248.000000
1930    151.000000
1940    224.000000
1950    235.750000
1960    313.727273
1970    172.333333
1980    246.420814
1990    262.669749
2000    240.688603
2010    293.674154
2020    336.693603
Name: paginas, dtype: float64

In [17]:
# 2 - Quais são os 10 autores com mais livros no dataset? Use value_counts() na coluna autor.

df_limpo["autor"].value_counts().head(10)

autor
Clarice Lispector    104
Rocco                 88
Rick Riordan          84
Meg Cabot             73
Augusto Cury          71
Paulo Coelho          70
J.K. Rowling          66
Planeta do Brasil     62
Lucasfilm Ltd.        59
Cassandra Clare       57
Name: count, dtype: int64

In [18]:
# 3 - Qual a distribuição de faixa_paginas para livros publicados após 2010? Filtre e use value_counts().

df_limpo[df_limpo["ano"] > 2010]["faixa_paginas"].value_counts()

faixa_paginas
Médio    4010
Longo    1961
Curto     970
Name: count, dtype: int64

In [19]:
# 4 - Exporte o df_limpo para um arquivo Excel chamado livros_analisados.xlsx.

df_limpo.to_excel("livros_analisados.xlsx", index=False)